hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FileDataServlet.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ListPathsServlet.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DelegationTokenFetcher.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/ByteRangeInputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/HftpFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/HsftpFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/WebHdfsFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenRenewer, hadoop-hdfs-project/hadoop-hdfs/src/site/apt/Hftp.apt.vm, hadoop-hdfs-project/hadoop-hdfs/src/test/aop/org/apache/hadoop/hdfs/TestFiHftp.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/MiniDFSCluster.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestListPathServlet.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAuditLogs.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestByteRangeInputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestHftpDelegationToken.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestHftpFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestHftpURLTimeouts.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-hs/src/test/resources/job_1329348432655_0001_conf.xml
Running SparkPi from code gets the exception below. I submit the Spark job as a Yarn job, the applicaton jar as local resource, the Spark jar is assumed to be in HDFS:
```
YarnClient yarnClient;
ApplicationSubmissionContext appContext;
yarnClient.submitApplication(appContext);
```
The error:
```
java.lang.UnsupportedOperationException: Not implemented by the HftpFileSystem FileSystem implementation
at org.apache.hadoop.fs.FileSystem.getScheme(FileSystem.java:214)
at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:2365)
at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2375)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2392)
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89)
at …
```
=> Error: HftpFileSystem does not implement getScheme

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestHAFileCreationMultipleNNFailure.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestHARead.java
TestHARead and TestHAFileCreationMultipleNNFailure are randomly failing. Probably because of race conditions. The test will be disabled for now. A second issue for revising these test cases was created.
=> Disable randomly failing HA tests

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/localizer/TestLocalResourcesTrackerImpl.java
add sleep time after call to handle to let the time to all the events triggered  by the handle call to be processed before the test run any verification.
Resolve #11
=> fix race condition in TestLocalResourcesTrackerImpl.testLocalResourceCache

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsStorageFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/INodeDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/MetadataLogContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/TestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestAccessTimeLog.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSizeLog.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSubtreeLock.java
Added, deleted and renamed files as well as per user access times and file sizes are written to speciel log tables and available for a consumer.
Directories do now have a metadata enabled flag. All operations in the filetree under an enabled directory will be logged.
It can be enabled per directory using DistributedFileSystem.setMetaEnabled(Path src, boolean metaEnabled).
=> This commit adds a metadata log for HopsWorks

hops-erasure-coding/src/main/java/io/hops/erasure_coding/BaseEncodingManager.java, hops-erasure-coding/src/main/java/io/hops/erasure_coding/Encoder.java, hops-erasure-coding/src/main/java/io/hops/erasure_coding/Helper.java, hops-erasure-coding/src/main/java/org/apache/hadoop/hdfs/server/datanode/BlockReconstructor.java, hops-erasure-coding/src/test/java/io/hops/erasure_coding/ClusterTest.java, hops-erasure-coding/src/test/java/io/hops/erasure_coding/TestErasureCodingManager.java, hops-erasure-coding/src/test/java/org/apache/hadoop/fs/TestErasureCodingFileSystem.java
Some erasure coding classes were expecting DistributedFileSystem to be used and crashed in case ErasureCodingFileSystem was used. This patch resolves this issue.
=> Make the erasure coding components work when the ErasureCodingFileSystem is configured as default

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/FSDownload.java
https://issues.apache.org/jira/browse/YARN-1914
=> YARN-1914: TestFSDownload.testDownloadPublicWithStatCache fails on Windows

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/main/java/org/apache/hadoop/yarn/server/applicationhistoryservice/FileSystemApplicationHistoryStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/test/java/org/apache/hadoop/yarn/server/applicationhistoryservice/TestFileSystemApplicationHistoryStore.java
the test fails because we are leaking a file-handle in the history service
https://issues.apache.org/jira/browse/YARN-1920
=> YARN-1920: TestFileSystemApplicationHistoryStore fails

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ApplicationMasterService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/NDBRMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/RMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/TestDistributedRTClient.java
Break the Heartbeat and allocate rpcs in sub part when persisting them to the database to avoid problems of rpc too big to fit in a row of the database
fix #57
=> fix rpc too big bug

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/CSQueueInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerAppInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/SchedulerApplicationInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ApplicationMasterService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/NDBRMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/RMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/SchedulerApplication.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/SchedulerApplicationAttempt.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/CapacityScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/LeafQueue.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fifo/FifoScheduler.java
Correct error that made that only one appAttempt was recovered per app
Correct error that made that FicaSchedulerAppInfo was not removed from the database if it add been updated in the same transaction
When recovering leafQueue the recover function was unsing appAttempt.isPending to decide to put the application in the pending queue or in the active queue but appAttempt.isPending and the leafQueue pending queue are not linked, introducing a new mechanism to persist the pending queue in the database
=> correct capacity scheduler recovery

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java
=> truncate containerStatus diagnostic to avoid it being too big for the database

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGeneratorFactory.java
Avoids weird scenario's due to multiple calls to setConfiguration()
Haven't run the tests yet.
=> Check if setConfiguration has been called >1 time

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsStorageFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/io/hops/metadata/util/YarnAPIStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hops-leader-election/src/main/java/io/hops/metadata/LEStorageFactory.java
add a -format option to the resourcemanager that format only the yarn tables in the db
depend on:
hopshadoop/hops-metadata-dal-impl-ndb#55
hopshadoop/hops-metadata-dal#46
=> Yarn formating

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/PriceFixerService.java
do not persist price history: it is not use right now and it is not garbage collected which result in a "memory leak"
=> do not persist price history

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java
Truncate the finished container diagnostics string to avoid it being too long to be stored in the database
=> just finished container diagnostics string too long to be stored in the database

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hops-erasure-coding/src/main/java/io/hops/erasure_coding/BaseEncodingManager.java, hops-erasure-coding/src/main/java/io/hops/erasure_coding/Encoder.java
Makes the erasure coding library play nice with heterogeneous storage.
See issue https://github.com/bcleenders/hops/issues/20 for more info.
It keeps the storage policy of the original file; if you wish to use EC+RAID5, just set the storage policy of the file to RAID5 and then erasurecode it. If you wish to use EC+All_SSD, just set the policy to All_SSD and then erasurecode it, etc.
You can also change the storage policy of an erasurecoded file (just call setStoragePolicy on it). However, this won't move the parity file(s). Even if you call Mover, only the data blocks move, not the parity block(s). This is due to the design of the EC library which stores the parity blocks as a separate file, which makes syncing the storage policies a bit more complicated.
Shouldn't be a problem for now, …
=> Ec on raid5

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/MetadataLogContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java
Add log entries for a subtree only when you rename across different metaEnabled directories
=> Fixes HOPS-35

hadoop-common-project/hadoop-common/pom.xml
After upgrading to 2.8.2 SysInfoLinux located in hadoop-common replaced LinuxResourceCalculatorPlugin located in hadoop-yarn-common. hadoop-common pom.xml needs to be updated to include hops-gpu-management depdendency.
=> HOPS-84 hadoop-common pom.xml should include hops-gpu-management dependency

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/io/hops/devices/GPUAllocator.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestCgroupsLCEResourcesHandlerGPU.java
This is not ok to bypass the normal testing process.
=> Revert "HOPS-82 Ignore unusable GPUs on NM"

hadoop-common-project/hadoop-common/src/main/conf/ssl-client.xml.example, hadoop-common-project/hadoop-common/src/main/conf/ssl-server.xml.example, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/FileBasedKeyStoresFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509KeyManager.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/KeyStoreTestUtil.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509KeyManager.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/site/markdown/EncryptedShuffle.md
[HOPS-147]  Implement a basic keystore manager
[HOPS-147]  Reloading thread
[HOPS-147]  Basic reloading testing for the key manager
[HOPS-147]  Test key manager when keystore is missing or corrupted
[HOPS-147]  Add more tests for reloading keystore manager
[HOPS-147]  Refactor key store factory to support reloadable key manager
[HOPS-147]  Add documentation
[HOPS-147]  Remove unused imports
https://hopshadoop.atlassian.net/browse/HOPS-147
=> [HOPS-147] Reloading SSL key manager

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeJspHelper.java
[HOPS-153] Take the HTTPS NameNode info port if SSL is enabled
[HOPS-153]  Register to leader election protocol with the correct http port
[HOPS-153]  Remove hard-code url scheme
=> [HOPS-153] Configure TLS REST API for NameNode

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java
[Hops-161] Fixed TestSmallFilesCreation.java. It took ~30 min on slow machines.
=> [HOPS-161] Fixed long TestsSmallFileCreation

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ClientCache.java
[HOPS-183]  Fix bug with cached Clients with old crypto material password
https://hopshadoop.atlassian.net/browse/HOPS-183
Bug fix. Bug reproducable when RPC TLS is enabled.
Invalidate Client cache in ClientCache if cached configuration and new do not match.
No breaking changes
=> [HOPS-183]  Fix bug with cached Clients when RPC TLS

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CryptoMaterial.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/CertificateLocalizationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/test/java/org/apache/hadoop/yarn/server/security/TestCertificateLocalizationService.java
https://hopshadoop.atlassian.net/browse/HOPS-186
Bugfix
See jira
No
=> [HOPS-186] CryptoMaterial buffers should be available for re-reading

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/allocator/RegularContainerAllocator.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/MockAM.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestCapacityScheduler.java
https://hopshadoop.atlassian.net/browse/HOPS-185
This makes it not possible for a container requiring 1 or more GPUs to reserve resources on a machine without GPUs
Skip container assignment if a node does not that GPUs.
No
=> [HOPS-185] do not reserve GPU containers on CPU machines

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/SSLFactory.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/HopsSSLTestUtils.java
https://hopshadoop.atlassian.net/browse/HOPS-258
Remove unsupported TLS/SSL versions and upgrade default TLS version for the client to TLSv1.2
No new behaviour
No breaking changes
=> [HOPS-258]  Change default TLS enabled protocols

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/UnderReplicatedBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestReplicationPolicy.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-337
=> [HOPS-337] fix replication index being stuck in UnderReplicatedBlocks

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/HeartbeatManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPServiceActor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/metrics/FSNamesystemMBean.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/RegisterCommand.java
Get DN storages out of blockContentsStale state faster after NN restarts. (Contributed by Ming Ma)
git-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1616680 13f79535-47bb-0310-9956-ffa450edef68
https://hopshadoop.atlassian.net/browse/HOPS-370
Improvement and feature. 
Adds a new metric (number of stale storages), and improves non-staleness reporting.
=> [HOPS-370] apply HDFS-6772. 

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/AbstractYarnScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestCapacityScheduler.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-396
Bug fix
Modification to use the Resource constructor with three arguments (memory, cpu, gpu). Previously it only used the one with two arguments (memory, cpu) which caused the gpu value to default to 0.
No
=> [HOPS-396] Fix where max GPU allocation is set to 0

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSubtreeLockACL.java
Fixing HOPS-5 ACL-induced bug with incorrect permission check for subtree ops causing TestDFSPermission to fail.
https://hopshadoop.atlassian.net/browse/HOPS-374
Bug fix
=> [HOPS-374] 

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/INodeDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java
[Hops-458] SubTree operation on a large directory with millions of immediate children can kill the database.
https://hopshadoop.atlassian.net/browse/HOPS-458
Bug fix
Nay
hopshadoop/hops-metadata-dal#114 and hopshadoop/hops-metadata-dal-impl-ndb#140
=> [HOPS-458] SubTree operation on a large directory with millions of immediate children can kill the database.

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/io/TestHopsUtil.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/main/java/org/apache/hadoop/mapreduce/v2/app/MRAppMaster.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestRMAppCertificateManager.java
[HOPS-492]  Testing HopsUtil generating client version of ssl-server.xml
[HOPS-492]  Generate client version of ssl-server.xml for MR jobs
https://hopshadoop.atlassian.net/browse/HOPS-492
Improvement, bug fix
MR AppMaster uses Hadoop's RPC server. When RPC TLS is enabled, ssl-server.xml should be configured properly for the server to start. This JIRA generates a client version of "ssl-server.xml" by writing the client configuration properties in that file.
* **Does this PR introduce a breaking change?** (What changes might users need to …
=> [HOPS-492]  Writing client ssl-server when RPC TLS is enabled

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java
https://hopshadoop.atlassian.net/browse/HOPS-550
Bug fix
Unsetting the MetaEnabled for a subtree won't write log entries to hdfs_metadata_log
=> [HOPS-550] Fix Unsetting MetaEnabled for a subtree

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/RemotePeerFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/JspHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeFsck.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/BlockReaderTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSSSLServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockTokenWithDFS.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDataNodeVolumeFailure.java
Temporary fix for BlockReader until we implement block transfer over TLS
https://hopshadoop.atlassian.net/browse/HOPS-624
*Temporary* bug fix until we implement block transfer over TLS
=> [HOPS-624]  Use the StandardSocketFactory in BlockReader when Hops TLS enabled

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/StorageMap.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockInfoUnderConstruction.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlocksMap.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/CorruptReplicasMap.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/HeartbeatManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/MiniDFSCluster.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestHeartbeatHandling.java
https://hopshadoop.atlassian.net/browse/HOPS-627
bug fix
when a NN becomes a leader it checks all the storages present in the database and removes the replicas for the storages that do not match a registered data node.
=> [HOPS-627] cleanup replicas from dead storages from the database.

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/HopsworksRMAppCertificateActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAppCertificateActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAppCertificateManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestingRMAppCertificateActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestRMAppCertificateManager.java
https://hopshadoop.atlassian.net/browse/HOPS-680
Improvement
Application keystore will contain its certificate/private key and the intermediate CA certificate as a bundle. Keystore will contain Hops Root CA certificate.
Also, https://logicalclocks.atlassian.net/browse/HOPSWORKS-697
=> [HOPS-680] Change application keystore structure and switch to Hopsworks CA V2

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
https://hopshadoop.atlassian.net/browse/HOPS-807
=> [HOPS-807] SetOwner should update the usersgroups cache on all namenodes

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-1101
=> [HOPS-1101] secondary NN initilaize repl queues even out of safe mode

hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/node/ActiveNode.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/node/ActiveNodePBImpl.java, hadoop-common-project/hadoop-common/src/main/proto/ActiveNode.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/FailoverProxyHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/HopsRandomStickyFailoverProxyProvider.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/proto/yarn_GroupMembership_service.proto, hops-leader-election/src/main/java/io/hops/leaderElection/HdfsLeDescriptorFactory.java, hops-leader-election/src/main/java/io/hops/leaderElection/LEContext.java, hops-leader-election/src/main/java/io/hops/leaderElection/LETransaction.java, hops-leader-election/src/main/java/io/hops/leaderElection/LeaderElection.java, hops-leader-election/src/main/java/io/hops/leaderElection/YarnLeDescriptorFactory.java
https://hopshadoop.atlassian.net/browse/HOPS-6
feature
Admins can assign a namenode to a specific availability zone using a new configuration parameter in hdfs-site. Users can also assign their clients to a specific availability zone to enforce using a namenode from the same availability zone.
https://github.com/hopshadoop/hops-metadata-dal/pull/150 …
=> [HOPS-6] Availability Zone Awareness support for HopsFS

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CertificateLocalization.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/CertificateLocalizationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/test/java/org/apache/hadoop/yarn/server/security/TestCertificateLocalizationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/ContainerSecurityUpdaterTask.java
[HOPS-1149]  Take exclusive file descriptor lock when updating crypto material for container
[HOPS-1149]  Remove IO operations from NM heartbeat loop
https://hopshadoop.atlassian.net/browse/HOPS-1149
Improvement
When NM receives an updated security material (X.509 or JWT), it acquires an exclusive lock on the file descriptor so another process (if it's a good citizen) would be blocked. Also, remove I/O operations for updating local files from NodeManager's heartbeat loop.
* **Does this PR introduce a breaking change?** (What changes might …
=> [HOPS-1149]  Take exclusive fd lock and remove I/O operations from NM's heartbeat loop

hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1348
feature change
feature change - XAttr
It changes the db. If anyone used XAttr and added values of max size - this would be a big breaking change.
https://github.com/hopshadoop/hops-metadata-dal/pull/165
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/206
=> [HOPS-1348] alter xattr table - decrease size of xattr value

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeDescriptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeStorageInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-1365
Bug fix
depends on hopshadoop/hops-metadata-dal#168 and hopshadoop/hops-metadata-dal-impl-ndb#209
=> [HOPS-1365] fix getBlocks to be faster and not kill the DB

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1395
bug fix
=> [HOPS-1395] Put back limit on number of elements in directory

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java
https://hopshadoop.atlassian.net/browse/HOPS-1439
Bug fix
=> [HOPS-1439] Fallback to default key manager reloading conf if can't read ssl-client

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/RemotePeerFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeFsck.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/BlockReaderTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSSSLServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockTokenWithDFS.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDataNodeVolumeFailure.java
https://hopshadoop.atlassian.net/browse/HOPS-1525
Bug fix
There is a configuration property in DFSConfigKeys which specifies what Socket Factory to use when talking to DataNode's Xceiver server. It defaults to StandardSocketFactory as xceiver server does not communicate over TLS
=> [HOPS-1525] Use configurable Socket Factory when connecting to DN's Xceiver instead of the DefaultSocketFactory

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/IndividualBlockLock.java
https://hopshadoop.atlassian.net/browse/HOPS-1550
Bug fix
=> [HOPS-1550] IndividualBlockLock.announceBlockDoesNotExist should not use global blockId variable

hadoop-common-project/hadoop-common/pom.xml, hadoop-common-project/hadoop-common/src/main/java/io/hops/net/ServiceDiscoveryClientFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSUtil.java, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1552
New feature
When Service Discovery is enabled we get NameNodes' RPC addresses from service discovery instead of the configuration file.
No breaking change
=> [HOPS-1552] DataNodes use Service Discovery to connect to NameNodes instead of static configuration file

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java
https://hopshadoop.atlassian.net/browse/HOPS-1580
bug fix
use rpc host for the leader election http address if the bind address for the http server is `0.0.0.0`
=> [HOPS-1580] fix leader election using bind address for http

hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/erasure_coding/TestUtil.java, hadoop-project/pom.xml
Bumps commons-compress from 1.4.1 to 1.19.
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump commons-compress from 1.4.1 to 1.19 in /hadoop-project

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMAppManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/AppManagerTestBase.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestAppManager.java
Partially applying [YARN-9848](https://issues.apache.org/jira/browse/YARN-9848) Not everything in the patch can be applied because in between `RMApp` has changed with respect to LogAggregation
https://hopshadoop.atlassian.net/browse/HOPS-1645
Finished applications will be removed from state store and memory regardless of their log aggregation status
No
=> [HOPS-1645] Partially apply YARN-9848 Remove apps from state store regardless of log aggregation state

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-common-project/hadoop-common/src/test/java/io/hops/security/TestHopsX509Authenticator.java
https://hopsworks.atlassian.net/browse/HOPSFS-146
=> [HOPSFS-146] Implement SIMPLE RPC authentication method where the CN should just be resolvable instead of matching the incoming RPC IP address
