hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/INodeDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/NamenodeSelector.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeJspHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsck.java, hadoop-hdfs-project/hadoop-hdfs/src/test/resources/log4j.properties, hops-leader-election/src/main/resources/log4j.properties
Fixed Performance Issures with dir listing
=> Fixed Performance Issures with dir listing

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsStorageFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/ReplicaUnderConstructionDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/InvalidatedBlockContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/ReplicaContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/ReplicaUnderConstructionContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BatchedBlocksRelatedLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BlockRelatedLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/SqlBatchedBlocksRelatedLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockInfoUnderConstruction.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/ReplicaUnderConstruction.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/metadata/lock/TestNDBSizer.java
read invalidated blocks by storageId
=> remove replica_index from replicas and replica_under_construction tables

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java
=> solve memory leak and remove "cycle too long" debug logs

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMContextImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestAppManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestClientRMService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMNodeTransitions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestTransactionStateManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/resourcetracker/TestNMExpiry.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/resourcetracker/TestNMReconnect.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/resourcetracker/TestRMNMRPCResponseId.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestCapacityScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestQueueParsing.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestUtils.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fifo/TestFifoScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/TestRMWebApp.java
=> reseting the transactionStateManager when transitioning to standby in order to not block on not finishing RPCs.

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbEventStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbRtStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java
Modification to use the lastest version of the streaming library. This is a result of hopshadoop/hops-metadata-dal-impl-ndb#28
=> modifications to use the lastest version of the streaming library.

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestAMAuthorization.java
YARN-1201: TestAMAuthorization fails with local hostname cannot be resolved
=> YARN-1201 https://issues.apache.org/jira/browse/YARN-1201

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMAdminService.java
=> apply yarn-1883

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/NodeStatusUpdaterImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/SchedulerApplicationAttempt.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/LeafQueue.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/common/fica/FiCaSchedulerNode.java
Turn info messages into debugging
=> YARN-1892 mainly turn info messages into debug

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/main/java/org/apache/hadoop/yarn/applications/distributedshell/Client.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/test/java/org/apache/hadoop/yarn/applications/distributedshell/TestDistributedShell.java
changes completed , tests look that run properly
=> YARN-1926 tests done

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/view/InfoBlock.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/test/java/org/apache/hadoop/yarn/webapp/view/TestInfoBlock.java
All tests passed successfully.
=> YARN-1932 tests done

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/main/java/org/apache/hadoop/yarn/applications/distributedshell/ApplicationMaster.java
https://issues.apache.org/jira/browse/YARN-1908
=> YARN-1908: Distributed shell with custom script has permission error.

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client/src/test/java/org/apache/hadoop/yarn/client/TestRMFailover.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/RMWebAppFilter.java
https://issues.apache.org/jira/browse/YARN-1898
=> Applying Yarn-1898

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client/src/test/java/org/apache/hadoop/yarn/client/api/impl/TestTimelineClient.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml
https://issues.apache.org/jira/browse/YARN-1962
=> Apply patch Yarn-1962

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/attempt/RMAppAttemptImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/attempt/TestRMAppAttemptTransitions.java.torewrite
https://issues.apache.org/jira/browse/YARN-1976
=> Apply patch YARN-1976

hadoop-yarn-project/hadoop-yarn/bin/yarn
https://issues.apache.org/jira/browse/YARN-1429
=> Apply patch YARN-1429

hadoop-tools/distributedLoadSimulator/src/main/java/org/apache/hadoop/distributedloadsimulator/sls/SLSRunner.java, hadoop-tools/distributedLoadSimulator/src/main/java/org/apache/hadoop/distributedloadsimulator/sls/appmaster/AMSimulator.java, hadoop-tools/distributedLoadSimulator/src/main/java/org/apache/hadoop/distributedloadsimulator/sls/scheduler/SLSCapacityScheduler.java, hadoop-tools/distributedLoadSimulator/src/main/java/org/apache/hadoop/distributedloadsimulator/sls/scheduler/SchedulerWrapper.java, hadoop-tools/distributedLoadSimulator/src/main/java/org/apache/hadoop/distributedloadsimulator/sls/web/SLSWebApp.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/SLSRunner.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/appmaster/AMSimulator.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/scheduler/ResourceSchedulerWrapper.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/scheduler/SLSCapacityScheduler.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/scheduler/SchedulerWrapper.java, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/web/SLSWebApp.java, hadoop-tools/hadoop-sls/src/test/resources/yarn-site.xml
https://issues.apache.org/jira/browse/YARN-1471
=> Applying YARN-1071

hadoop-yarn-project/hadoop-yarn/bin/yarn, hadoop-yarn-project/hadoop-yarn/bin/yarn.cmd, hadoop-yarn-project/hadoop-yarn/conf/yarn-env.sh
https://issues.apache.org/jira/browse/YARN-1982
=> Applying YARN-1982

hadoop-common-project/hadoop-common/src/site/apt/ClusterSetup.apt.vm
https://issues.apache.org/jira/browse/YARN-2036
=> Applying YARN-2036

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/QueuePlacementRule.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/TestFairScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/TestQueuePlacementPolicy.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/apt/FairScheduler.apt.vm
https://issues.apache.org/jira/secure/attachment/12646607/YARN-2012-v3.txt
https://issues.apache.org/jira/browse/YARN-2105
=> Yarn 2012 and YARN-2105

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ClusterJspHelper.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapreduce/v2/TestRMNMInfo.java, hadoop-project/pom.xml, hadoop-tools/hadoop-sls/src/main/java/org/apache/hadoop/yarn/sls/RumenToSLSConverter.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/timeline/TimelineUtils.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/YarnJacksonJaxbJsonProvider.java
https://issues.apache.org/jira/browse/HADOOP-10104
* HADOOP-10104 Change version of jackson library
* HADOOP-10104 Update jackson api
=> HADOOP-10104

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/native/container-executor/impl/container-executor.c
https://issues.apache.org/jira/browse/YARN-1940
=> Apply YARN-1940

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestClientRMService.java
https://issues.apache.org/jira/browse/YARN-1977
=> Applying YARN-1977

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/ContainerManagerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/TestContainerManagerSecurity.java
https://issues.apache.org/jira/browse/YARN-2065
=> Apply YARN-2065

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/logaggregation/LogCLIHelpers.java
https://issues.apache.org/jira/secure/attachment/12644778/YARN-2050-2.patch
=> Apply YARN-2050

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/QueuePlacementPolicy.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/QueuePlacementRule.java
https://issues.apache.org/jira/browse/YARN-2089
=> Apply YARN-2089

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/api/records/ContainerExitStatus.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/ContainerManagerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/application/ApplicationImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/container/ContainerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/container/ContainerKillEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/monitor/ContainersMonitorImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/TestContainerManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/container/TestContainer.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/launcher/TestContainerLaunch.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/monitor/TestContainersMonitor.java
https://issues.apache.org/jira/browse/YARN-2091
=> Apply YARN-2091

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/CapacityScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestCapacityScheduler.java
https://issues.apache.org/jira/browse/YARN-2171
=> Apply patch YARN-2171

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/SchedulingMonitor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/capacity/ProportionalCapacityPreemptionPolicy.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/MockRM.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/capacity/TestProportionalCapacityPreemptionPolicy.java
https://issues.apache.org/jira/browse/YARN-2124
=> Apply YARN-2124

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/main/java/org/apache/hadoop/yarn/server/applicationhistoryservice/timeline/security/TimelineACLsManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/main/java/org/apache/hadoop/yarn/server/applicationhistoryservice/webapp/TimelineWebServices.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/test/java/org/apache/hadoop/yarn/server/applicationhistoryservice/timeline/security/TestTimelineACLsManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/test/java/org/apache/hadoop/yarn/server/applicationhistoryservice/webapp/TestTimelineWebServices.java
https://issues.apache.org/jira/browse/YARN-2059
=> Apply YARN-2059

hadoop-common-project/hadoop-auth/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMDelegationTokenSecretManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/RMWebServices.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/dao/DelegationToken.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/TestRMWebServicesDelegationTokens.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/apt/ResourceManagerRest.apt.vm
https://issues.apache.org/jira/secure/attachment/12655816/apache-yarn-2233.5.patch
=> Apply YARN-2233

hadoop-common-project/hadoop-auth/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/http/RMAuthenticationFilter.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/http/RMAuthenticationFilterInitializer.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAuthenticationHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMDelegationTokenSecretManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/RMWebServices.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/dao/DelegationToken.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/TestRMWebServicesDelegationTokenAuthentication.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/TestRMWebServicesDelegationTokens.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/webapp/TestRMWebappAuthentication.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-site/src/site/apt/ResourceManagerRest.apt.vm
https://issues.apache.org/jira/secure/attachment/12658026/YARN-2247.6.patch
=> Yarn 2247 new

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/io/hops/ha/common/TransactionState.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/AgregatedAppInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerAppInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerNodeInfoAgregate.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerNodeInfoToUpdate.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/RMNodeInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/RMNodeInfoAgregate.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/transactionStateWrapper.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbEventStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbRtStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/RMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmcontainer/RMContainerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmnode/RMNodeImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/SchedulerApplicationAttempt.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/CapacityScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/common/fica/FiCaSchedulerApp.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/common/fica/FiCaSchedulerNode.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fifo/FifoScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/QuotaService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/io/hops/ha/common/TestDBLimites.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/io/hops/metadata/util/TestHopYarnAPIUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestContainersLogsService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/rmcontainer/TestRecoverRMContainerImpl.java
Container information should now be correctly removed from the database.
=> Remove container info db

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/transactionStateWrapper.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/SchedulingMonitor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/capacity/ProportionalCapacityPreemptionPolicy.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/NDBRMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/RMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/monitor/capacity/TestProportionalCapacityPreemptionPolicy.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestRecoverCapacityScheduler.java
Recover CS preempted containers
=> Persist CS preempted containers in ndb

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/io/hops/metadata/util/HopYarnAPIUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/client/ConfiguredRMFailoverHAProxyProvider.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMNodeTransitions.java
correct race condition in the starting and stopping of the resource t…racker services.
Change proxy provider to retry to connect until getting a connection even if none of the resource tracking nodes are reachable immediately.
=> correct race condition in resourceTracker

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ContainersLogsService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbRtStreamingProcessor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbRtStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMContextImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/StreamingRTComps.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/PriceFixerService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/QuotaService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/TestFSLeafQueue.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/TestFairSchedulerEventLog.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/TestQuotaService.java
Add a service that set the current price in function of the cluster usage
Use the fixed price when charging containers
=> Add ubber pricing done by Rizvi

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/main/java/org/apache/hadoop/yarn/applications/distributedshell/ApplicationMaster.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/io/hops/ha/common/TransactionState.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerAppInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerNodeInfoAgregate.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/FiCaSchedulerNodeInfoToUpdate.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/RMNodeInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/SchedulerApplicationInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/TransactionStateImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/ha/common/transactionStateWrapper.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMUtilities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/GroupMembershipService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbEventStreamingProcessor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/PendingEventRetrievalBatch.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMAppManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/NDBRMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/RMAppImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/attempt/RMAppAttemptImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmnode/RMNodeImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/AppSchedulingInfo.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/QueueMetrics.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/LeafQueue.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/ParentQueue.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/common/fica/FiCaSchedulerNode.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/TestRecoverCapacityScheduler.java
Correct missing transaction-sate locking to commit related transaction states in the good order.
Correctly persist and recover justFinishedContainers
Commit appAttempt State only when usefull.
Name threads
Variable name corrections
=> Correct parrallel comit and other small corrections

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/NdbRtStreamingReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMContextImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/quota/TestPriceEstimationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/resources/RT_EventAPIConfig.ini
correct bug with the streaming library not accepting float
=> Rizvi stream float

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/MetadataLogContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java
Use timestamps instead of logicaltime
=> Added INode ParentId and Name to hdfs_metadata_log

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java
Solve bug with containers statuses in heartbeats being too big.
=> Container status too big in heartbeat

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsGroupsWithFallBack.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroups.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroupsCache.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/CountersQueue.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsStorageFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/resolvingcache/InMemoryCache.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/metadata/TestHdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroups.java, hadoop-tools/hadoop-extras/src/test/java/org/apache/hadoop/tools/TestCopyFiles.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/io/hops/metadata/util/YarnAPIStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/metadata/util/RMStorageFactory.java
Merged hops/develop into bcleenders/master, now merging bcleenders/master into hops/develop-heterogeneous-storage, so that it has all changes made in develop.
=> Merge in changes from hops/develop

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/BlockInfoContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/ReplicaUnderConstructionContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/IndividualBlockLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LastTwoBlocksLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/MutableBlockCollection.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFileUnderConstruction.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/Lease.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java
- added last_block_id and penultimate_block_id to leasepath
- fixed incremental block report to only read the required block from the database
=> Fixes HOPS-17

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
add number of live and dead datanode to the measurements to be able to get their value in graphite
https://hopshadoop.atlassian.net/browse/HOPSWORKS-74
=> HOPSWORKS-74

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsLocatedFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/JsonUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestJsonUtil.java
https://hopshadoop.atlassian.net/browse/HOPS-34
=> HOPS-34: HdfsFileStatus should return the fileId

hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroups.java
added a test to check for username/groupname case sensitivity
=> Fixes HOPS-44

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/security/Users.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroups.java
Catch UniqueKeyConstaintViolation exception in NameNode initialization
=> Fixes HOPS-48

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroups.java
Handled ForeignKeyConstraintViolationException in setOwner and added some test cases
=> Fixes HOPS-51 and HOPS-56

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/NameNodeAdapter.java
Includes:
- redundant throws declarations
- typos
- redundant initializers
=> [HOPS-58] Fixing ~300 code quality issues in FSNamesystem.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
HOPS-58 introduced an audit event logging bug.
=> HOPS-58-fix fix incorrectly modified audit event log

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/logaggregation/AppLogAggregatorImpl.java
[HOPS-79] Undo in-house changes that fix the Log Aggregation issue with the LogWriter
[HOPS-79] Apply patch YARN-7083 from upstream which fixes the Log Aggregation issue
https://hopshadoop.atlassian.net/browse/HOPS-79
=> HOPS-79 Fix Log Aggregation with upstream patch

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsck.java
[HOPS-78] Fix case for regular expression pattern
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-78
=> [HOPS-78] Fix case for regular expression pattern

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/LinuxContainerExecutor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandlerGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/DefaultLCEResourcesHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/LCEResourcesHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/native/container-executor/impl/container-executor.c, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/native/container-executor/impl/container-executor.h, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/native/container-executor/impl/main.c, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/TestLinuxContainerExecutor.java
HOPS-83 Cgroups hierarchy is created automatically and NM permissions set
=> HOPS-83 Cgroups hierarchy is created automatically

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/io/hops/devices/GPUAllocator.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandlerGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestCgroupsLCEResourcesHandlerGPU.java
HOPS-82 Ignore unusable GPUs on NM
=> HOPS-82 Ignore unusable GPUs on NM

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandlerGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/native/container-executor/impl/container-executor.c
HOPS-89 Fix Cgroup ownership bug
=> HOPS-89 Fix Cgroup ownership bug

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/fs/Hdfs.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/web/resources/NamenodeWebHdfsMethods.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/WebHdfsFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/resources/FsActionParam.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/resources/GetOpParam.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/site/apt/WebHDFS.apt.vm, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSPermission.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSafeMode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsFileSystemContract.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsUrl.java
https://hopshadoop.atlassian.net/browse/HOPS-96
=> [HOPS-96] Added checkAccess rpc to DFS based on HDFS-6570

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java
Fix path to ssl-server.xml
https://hopshadoop.atlassian.net/browse/HOPS-100
=> [HOPS-100] Fix path to ssl-server.xml

hadoop-hdfs-project/hadoop-hdfs/src/main/native/libhdfs/hdfs.c
https://hopshadoop.atlassian.net/browse/HOPS-108
=> [HOPS-108] Set HDFS username in native libhdfs

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/BlockReaderDB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BRTrackingService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFileSeek.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java
Fixed commits history from  #393
=> Fixed HOPS-111, HOPS-107, HOPS-112

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/INodeDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/MetadataLogContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java
https://hopshadoop.atlassian.net/browse/HOPS-97
=> [HOPS-97] Use logical time per inode instead of timestamp for ordering

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/streaming/RmNodeApplicationsEventReceiver.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/util/RMStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/util/YarnAPIStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/io/hops/TestStreaming.java, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-127
https://hopshadoop.atlassian.net/browse/HOPS-128
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-124
Needs hopshadoop/hops-metadata-dal#95
Needs hopshadoop/hops-metadata-dal-impl-ndb#110
Needs hopshadoop/hops-gpu-management#2
Needs hopshadoop/hops-gpu-management-impl-nvidia#6
=> [HOPS-124], [Hops-128] and [Hops-127]

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/quota/QuotaService.java
https://hopshadoop.atlassian.net/browse/HOPS-130
https://hopshadoop.atlassian.net/browse/HOPS-131
=> Hops-130 and HOPS-131

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmnode/RMNodeImplDist.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmnode/RMNodeImplNotDist.java
https://hopshadoop.atlassian.net/browse/HOPS-136
=> [HOPS-136] log lost containers.

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/quota/ContainersLogsService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/quota/QuotaService.java
removing containers log and checkpoint from the database when the container is in a final state even if there is no quota utilization.
https://hopshadoop.atlassian.net/browse/HOPS-140
=> [HOPS-140]

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/IndividualINodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSOutputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesQuota.java
https://hopshadoop.atlassian.net/browse/HOPS-137
https://hopshadoop.atlassian.net/browse/HOPS-109
=> [HOPS-137] fixed issues with small file quota calcuation

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RpcSSLEngine.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RpcSSLEngineAbstr.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ServerRpcSSLEngineImpl.java
Dynamically enlarge sslUnwrappedBuffer of server while reading from channel
https://hopshadoop.atlassian.net/browse/HOPS-145
=> [HOPS-145]  Dynamically enlarge sslUnwrappedBuffer

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/LastUpdatedContentSummary.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/DFSTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestQuota.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesQuota.java
https://hopshadoop.atlassian.net/browse/HOPS-139
=> [HOPS-139] added a new rpc to get last updated ContentSummary 

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/quota/ContainersLogsService.java
https://hopshadoop.atlassian.net/browse/HOPS-143
https://hopshadoop.atlassian.net/browse/HOPS-144
=> [HOPS-143] and [HOPS-144]

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/quota/QuotaService.java
https://hopshadoop.atlassian.net/browse/HOPS-149
Depends on hopshadoop/hops-metadata-dal#96 and hopshadoop/hops-metadata-dal-impl-ndb#113
=> [HOPS-149] add application IDs in project daily cost

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/AbstractHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/EnvVariableHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/HopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/HopsSSLCryptoMaterial.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/LocalResourceHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/NormalUserCertLocServiceHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/NormalUserMaterilizeDirSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/SSLMaterialAlreadyConfiguredException.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/SuperUserHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/envVars/EnvironmentVariables.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/envVars/EnvironmentVariablesFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/envVars/SystemEnvironmentVariables.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSSSLServer.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/CertificateLocalizationService.java
[HOPS-158]  Base for various crypto material checks
[HOPS-158]  Write all the checks in different check classes. I should now be able to call them in HopsSSLSocketFactory
[HOPS-158]  Most of the tests in TestHopsSSLSocketFactory pass...
[HOPS-158]  Fix bug with checks ordering
[HOPS-158]  Fix failing tests for new HopsSSLSocketFactory
[HOPS-158]  Putting out the fire with gasoline. Cleaning up and JavaDoc
[HOPS-158] Formatting issues
https://hopshadoop.atlassian.net/browse/HOPS-158
=> [HOPS-158] Refactor HopsSSLSocketFactory crypto material checks and add new check

.github/pull_request_template.md
https://hopshadoop.atlassian.net/browse/HOPS-159
=> [HOPS-159]  Add PR template

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-170
Bug fix
=> [Hops-170] fixed slow deletion of large directories

hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java
https://hopshadoop.atlassian.net/browse/HOPS-183
Unit test for https://github.com/hopshadoop/hops/pull/437
No breaking changes
=> [HOPS-183-amend]  Unit test for ClientCache with new certificates

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/server/api/ApplicationInitializationContext.java
https://hopshadoop.atlassian.net/browse/HOPS-205
=> [HOPS-201]

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/TrashPolicyDefault.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/security/token/delegation/DelegationTokenSecretManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeHttpServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeJspHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/StartupProgressServlet.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/AbstractTracking.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/Phase.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/PhaseTracking.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StartupProgress.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StartupProgressMetrics.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StartupProgressView.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/Status.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/Step.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StepTracking.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StepType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/package-info.java, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.jsp, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/static/hadoop.css, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseRecovery2.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNameNodeJspHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestStartupProgressServlet.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StartupProgressTestHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/TestStartupProgress.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/TestStartupProgressMetrics.java
https://hopshadoop.atlassian.net/browse/HOPS-259
https://hopshadoop.atlassian.net/browse/HOPS-260
https://hopshadoop.atlassian.net/browse/HOPS-261
https://hopshadoop.atlassian.net/browse/HOPS-262
https://hopshadoop.atlassian.net/browse/HOPS-263
=> [HOPS-259], [HOPS-260], [HOPS-261], [HOPS-262] and [HOPS-263]

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java
https://hopshadoop.atlassian.net/browse/HOPS-280
=> [HOPS-280]

hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/HopsSSLTestUtils.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/KeyStoreTestUtil.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestCRLValidator.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestRevocationListFetcher.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSStartupWithCRL.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/TestYarnStartupWithCRL.java
[HOPS-321-amend]  Fix NPE bug with classpath
https://hopshadoop.atlassian.net/browse/HOPS-321
Bug fix
=> [HOPS-321-amend]  Amend of HOPS-321 fixing NPE wtih Test{DFS,Yarn}SSLServer

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java
https://hopshadoop.atlassian.net/browse/HOPS-323
=> [Hops-323] Inode locks acquirer fails when a client holds multiple leases

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-350
=> [HOPS-350] Update ClusterJ to 7.5.10

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-351
=> [HOPS-351] added profiles to enable building on Mac and Linux machines

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java
https://hopshadoop.atlassian.net/browse/HOPS-366
=> [HOPS-366] handle exceptions in block report

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/InvalidateBlocks.java
https://hopshadoop.atlassian.net/browse/HOPS-368
=> [HOPS-368] fix NPE for invalidating work on dead datanodes.

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/NormalUserCertLocServiceHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/NormalUserMaterilizeDirSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CertificateLocalization.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CryptoMaterial.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/main/java/org/apache/hadoop/yarn/server/security/CertificateLocalizationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-common/src/test/java/org/apache/hadoop/yarn/server/security/TestCertificateLocalizationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/LinuxContainerExecutor.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/ContainerManagerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/logaggregation/LogAggregationService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAppCertificateManager.java
https://hopshadoop.atlassian.net/browse/HOPS-342
Bug fix
No external API breaking change
=> [HOPS-342]  Refactor CertificateLocalizationService to be thread safer

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeMXBean.java, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfs-dust.js, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.js, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/explorer.js
https://hopshadoop.atlassian.net/browse/HOPS-461
=> [HOPS-461] fix HDFS web UI for proxy servlet.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataXceiver.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/BlockPoolSlice.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/tools/DelegationTokenFetcher.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/HftpFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFSOutputSummer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseRecovery.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDiskError.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAuditLogs.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestINodeFile.java
https://hopshadoop.atlassian.net/browse/HOPS-464
https://hopshadoop.atlassian.net/browse/HOPS-465
https://hopshadoop.atlassian.net/browse/HOPS-466
https://hopshadoop.atlassian.net/browse/HOPS-471
https://hopshadoop.atlassian.net/browse/HOPS-472
https://hopshadoop.atlassian.net/browse/HOPS-473
https://hopshadoop.atlassian.net/browse/HOPS-474
=> [HOPS-464], [HOPS-465], [HOPS-466], [HOPS-471], [HOPS-472], [HOPS-473] and [HOPS-474]

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-475
Need hopshadoop/hops-metadata-dal-impl-ndb#141
=> [HOPS-475] update clusterj to 7.6.6

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/LayoutVersion.java
https://hopshadoop.atlassian.net/browse/HOPS-483
=> [HOPS-483] fix ACL layout version

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-484
Needs hopshadoop/hops-metadata-dal#117
=> [HOPS-484] multythread processMisReplicatedBlocks

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroups.java
https://hopshadoop.atlassian.net/browse/HOPS-520
Bug fix
=> [HOPS-520] fix UsersGroups.getGroupsFromDB() to always commit.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/INodeDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/MDCleaner.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFailedSTOLockCleaner.java, hops-leader-election/src/main/java/io/hops/leaderElection/LEContext.java, hops-leader-election/src/main/java/io/hops/leaderElection/LETransaction.java, hops-leader-election/src/main/java/io/hops/leaderElection/LeaderElection.java
https://hopshadoop.atlassian.net/browse/HOPS-477
bug fix 
=> [HOPS-477] Added GC for STO locks left by dead namenodes

hadoop-hdfs-project/hadoop-hdfs/src/main/native/libhdfs/test_libhdfs_threaded.c
https://hopshadoop.atlassian.net/browse/HOPS-213
=> [HOPS-213] addendum correct bad merge on test_libhdfs_thread.c

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-570
dependency update
=> [HOPS-570] update NDB to 7.6.7

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-571
Bug fix
=> [HOPS-571] use bbc1 repo instead of kompics

hadoop-hdfs-project/hadoop-hdfs/CHANGES.txt, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/fs/Hdfs.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/BlockStorageLocationUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/client/ShortCircuitReplica.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNodeFaultInjector.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsVolumeImpl.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/WebHdfsFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/explorer.html, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestEnhancedByteBufferAccess.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/BlockReaderTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/FSAclBaseTest.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFileContextAcl.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsLimits.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNameNodeAcl.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHDFSAcl.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsTokens.java
https://hopshadoop.atlassian.net/browse/HOPS-560
https://hopshadoop.atlassian.net/browse/HOPS-561
https://hopshadoop.atlassian.net/browse/HOPS-562
https://hopshadoop.atlassian.net/browse/HOPS-563
https://hopshadoop.atlassian.net/browse/HOPS-564
https://hopshadoop.atlassian.net/browse/HOPS-565
https://hopshadoop.atlassian.net/browse/HOPS-566
https://hopshadoop.atlassian.net/browse/HOPS-567
https://hopshadoop.atlassian.net/browse/HOPS-568
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
=> [HOPS-560], [HOPS-561], [HOPS-562], [HOPS-563], [HOPS-564], [HOPS-565], [HOPS-566], [HOPS-567] and [HOPS-568]

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeWithAdditionalFields.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/TestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java
https://hopshadoop.atlassian.net/browse/HOPS-610
=> [HOPS-610] Add rename and setOwner as events in metadata_log

hops-leader-election/src/main/java/io/hops/leaderElection/LeaderElection.java
https://hopshadoop.atlassian.net/browse/HOPS-626
Bug fix
=> [HOPS-626]  Fix bug with LE protocol falsely assuming there is a leader

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/INodeUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-628
performance fix
improve replicas removal efficiency.
Depends on hopshadoop/hops-metadata-dal#125 and hopshadoop/hops-metadata-dal-impl-ndb#155
=> [HOPS-628] make the replicas removal more efficient.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-630
add logs
=> [HOPS-630] print log when block report processing fail.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/INodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/transaction/lock/TestInodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestGetBlocks.java
https://hopshadoop.atlassian.net/browse/HOPS-636
Bug fix
=> [HOPS-636] fix INodeLock for multiple paths

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/INodeUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-635
bug fix
=> [HOPS-635] fallback on prc-addres when servicerpc-addres is not set.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGeneratorFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/StorageInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/startupprogress/StartupProgress.java, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.js
https://hopshadoop.atlassian.net/browse/HOPS-649
https://hopshadoop.atlassian.net/browse/HOPS-650
bug fix
fix bugs in web ui and in variable table
=> [HOPS-649] and [HOPS-650]

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/SafeMode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/security/token/block/TestBlockToken.java
https://hopshadoop.atlassian.net/browse/HOPS-653
Bug fix
=> [HOPS-653] check replication before to set a block as safe.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/blockmanagement/ExcessReplicasMap.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-654
Bug fix
Depends on hopshadoop/hops-metadata-dal#130 and hopshadoop/hops-metadata-dal-impl-ndb#161
=> [HOPS-654] get excess replica metric from DB

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
https://hopshadoop.atlassian.net/browse/HOPS-675
bug fix
=> [HOPS-675] corect misreplicated number of threads configuration.

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java
When authenticating a connection from a daemon, use the FQDN instead of hostname. Use an Eviction cache instead of Set
https://hopshadoop.atlassian.net/browse/HOPS-674
Bug fix
Since https://logicalclocks.atlassian.net/browse/HOPSWORKS-582, X509 certificates contain the FQDN as CN instead of the hostname
Added code for backwards compatibility.
=> [HOPS-674] Use FQDN instead of hostname when authenticating Hops daemon

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/INodeUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSPermissionChecker.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSPermission.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFsShellPermission.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSPermissionChecker.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSubtreeLockACL.java
https://hopshadoop.atlassian.net/browse/HOPS-679
https://hopshadoop.atlassian.net/browse/HOPS-681
=> [HOPS-679] and [HOPS-681]

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CRLValidator.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/CRLValidatorFactory.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestCRLValidator.java
[HOPS-685] Fix Hops CRL validator
[HOPS-685] Trim material password
https://hopshadoop.atlassian.net/browse/HOPS-685
Bug fix
Related to https://logicalclocks.atlassian.net/browse/HOPSWORKS-697
=> [HOPS-685] Fix Hops CRL validator

hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
https://hopshadoop.atlassian.net/browse/HOPS-682
=> [HOPS-682] fixed hdfs-default.xml for block report load balancing

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-693
=> HOPS-693] fix retry cache cleaner.

hadoop-project/pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-697
=> [HOPS-697] update com.fasterxml.jackson.core dependency

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
https://hopshadoop.atlassian.net/browse/HOPS-746
This api is only used my our benchmark tool. This is simple change. It can be merged without testing
=> [HOPS-746] Fixed client API to get number of alive namenodes.

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeys.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CopyCommands.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/shell/find/TestFind.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMultithreadedCopyFromLocal.java
https://hopshadoop.atlassian.net/browse/HOPS-677
performance improvement
faster
no
=> [HOPS-677] Parallelize -copyFromLocal

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetworkTopology.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetworkTopologyWithNodeGroup.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/TestNetworkTopologyWithNodeGroup.java, hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService.java, hadoop-hdfs-project/hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/server/TestHttpFSServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/BlockReaderLocalLegacy.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BlockReceiver.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DNConf.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/DataNodeLayoutVersion.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/FsDatasetSpi.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetAsyncDiskService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetImpl.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsVolumeList.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/explorer.js, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestComputeInvalidateWork.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/SimulatedFSDataset.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/net/TestNetworkTopology.java
https://hopshadoop.atlassian.net/browse/HOPS-714
https://hopshadoop.atlassian.net/browse/HOPS-715
https://hopshadoop.atlassian.net/browse/HOPS-716
https://hopshadoop.atlassian.net/browse/HOPS-717
https://hopshadoop.atlassian.net/browse/HOPS-718
https://hopshadoop.atlassian.net/browse/HOPS-719
https://hopshadoop.atlassian.net/browse/HOPS-720
https://hopshadoop.atlassian.net/browse/HOPS-721
https://hopshadoop.atlassian.net/browse/HOPS-722
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
=> [HOPS-714], [HOPS-715], [HOPS-716], [HOPS-717], [HOPS-718], [HOPS-719], [HOPS-720], [HOPS-721] and [HOPS-722]

hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
https://hopshadoop.atlassian.net/browse/HOPS-369
=> [HOPS-369] fix dfs.blockreport.intervalMsec in hdfs-default.xml

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-803
=> [HOPS-803] clean up debug prints/logs

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/DatanodeInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BRTrackingService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java
https://hopshadoop.atlassian.net/browse/HOPS-805
=> [HOPS-805] reduce logging of BRLoadBalancingException and setCacheUsed

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-809
=> [HOPS-809] Check if retryCache is enabled before acquiring its lock

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/HopsRandomStickyFailoverProxyProvider.java
https://hopshadoop.atlassian.net/browse/HOPS-816
bug fix
improved randomization
=> Improve randomization in HopsRandomStickyFailoverProxyProvider

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroups.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroupsCache.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroups.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroupsMultiNamenode.java
https://hopshadoop.atlassian.net/browse/HOPS-812
=> [HOPS-812] setOwner shouldn't add the owner user to the owner group

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-820
=> [HOPS-820] Fix safe block counts during startup.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BlockRelatedLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/HashBucketsLocksAllFileBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockReport2.java
https://hopshadoop.atlassian.net/browse/HOPS-769
bug fix
=> [HOPS-769] Block report hash mismatch when files are deleted.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestHAFileCreation.java
https://hopshadoop.atlassian.net/browse/HOPS-819
=> [Hops 819] Close leader NN and other namenode proxies in DFSClient.close

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-827
=> [HOPS-827] Fix dead lock in FSNamesystem.addSafeBlocks

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ServerRpcSSLEngineImpl.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/RpcTLSUtils.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestCRLValidator.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestTLSRPCServer.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/TestYarnSSLServer.java
[HOPS-846]  Reuse some common TLS RPC utilities
https://hopshadoop.atlassian.net/browse/HOPS-846
Bug fix
=> [HOPS-846]  Chunk TLS payload if it exceeds NIO buffer limit

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeys.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CopyCommands.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/ParallelCommandWithDestination.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMultithreadedCopyToOrFromLocal.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-860?filter=allopenissues
feature
improved performance
nope
I am sleepy
=> [HOPS-860] Parallelized -copyToLocal HDFS CLI

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-863
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/176
=> [HOPS-863] Upgrade ClusterJ to 7.6.8

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-867
bug fix
https://github.com/hopshadoop/hops-metadata-dal/pull/144
=> [HOPS-867] Fixing string equality

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockPlacementPolicyDefault.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-891
=> [HOPS-891] prevent NullPointers in FSNamesystem.getAdditionalDatanode

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-997
=> [HOPS-997] update blocks metrics on non leading NN

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java
BPOfferService.blockReport should call blockReportCompleted in a finnaly
- [] Tests for the changes have been added and passed (for bug fixes / features)
https://hopshadoop.atlassian.net/browse/HOPS-920?filter=-1
bug fix
no
=> [HOPS-920] BPOfferService.blockReport should call blockReportCompleted in a finnaly

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/LightWeightGSet.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGeneratorFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BRTrackingService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hops-leader-election/src/main/java/io/hops/leaderElection/LETransaction.java, hops-leader-election/src/main/java/io/hops/leaderElection/LeaderElection.java
https://hopshadoop.atlassian.net/browse/HOPS-1010
update
improved logging
no
No need to run tests just merge it. All of the three projects have been updated
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/179
https://github.com/hopshadoop/hops-metadata-dal/pull/147
=> [HOPS-1010] Removing useless logs that are printed at INFO loggin level

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java
https://hopshadoop.atlassian.net/browse/HOPS-1013
Bug fix
=> [HOPS-1013] Fix get completedScanCount and curScanCount after update

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPServiceActor.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestPutCLIWithMultiNN.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockRecovery.java
https://hopshadoop.atlassian.net/browse/HOPS-28
updates
no
=> [HOPS-28] Added Unit Tests for put CLI using multiple NNs

hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs
https://hopshadoop.atlassian.net/browse/HOPS-1046
=> [HOPS-1046] disable OmitStackTraceInFastThrow

pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1047
depends on hopshadoop/hops-metadata-dal-impl-ndb#180
=> [HOPS-1047] update ndb to 7.6.9

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1085
Bug fix
=> [HOPS-1085] fix neededScanCount and completedScanCount on update

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/RetryCacheEntryLock.java
https://hopshadoop.atlassian.net/browse/HOPS-1102
=> [HOPS-1102] fix Tuple did not exist in RetryCacheCleaner

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BRTrackingService.java
* https://hopshadoop.atlassian.net/browse/HOPS-1100
Depends on  hopshadoop/hops-metadata-dal#151 and hopshadoop/hops-metadata-dal-impl-ndb#184
=> [HOPS-1100] BRTrackingService.assignWork in one transaction.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1093
bugfix
=> [HOPS-1093] Fixing NPE in Lease Manager caused by HOPS-1031

hadoop-hdfs-project/hadoop-hdfs/CHANGES.txt, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/HashBucketsLocksAllFileBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/IndividualHashBucketLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/HashBuckets.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/BlockReport.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/Bucket.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/DatanodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockReport2.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1108?filter=allopenissues
update
fewer false positives in block report hashes
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/185
https://github.com/hopshadoop/hops-metadata-dal/pull/152
=> [HOPS-1108] Change the plus operator to XOR for combining hashes in the block reporting system

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/FileBasedKeyStoresFactory.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/io/TestHopsUtil.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509KeyManager.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509TrustManager.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1012
=> [HOPS-1012] Extend ssl-server.xml with passwordfile location

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/HopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestHopsworksRMAppSecurityActions.java
https://hopshadoop.atlassian.net/browse/HOPS-1145
Bug fix
=> [HOPS-1145]  Set JWT's subject to be the username instead of the project specific username for Hopsworks security actions

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ClientCache.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/RevocationListFetcherService.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java
[HOPS-1155]  Remove Client cache invalidation
[HOPS-1155]  Reduce the minimum CRL fetcher service interval
https://hopshadoop.atlassian.net/browse/HOPS-1155
Bug fix
=> [HOPS-1155]  Remove Client cache invalidation

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/BlockReport.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestProcessCorruptBlocks.java
https://hopshadoop.atlassian.net/browse/HOPS-1201
Bux fix
=> [HOPS-1201] fix block reporting to correctly handle corrupt blocks

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/blockmanagement/ExcessReplicasMap.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeStorageInfo.java
https://hopshadoop.atlassian.net/browse/HOPS-1115?filter=-1
=> [HOPS-1115] Change FTIS to PPIS operation in Excess Replica Map

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetUtils.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/SuperUserHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/MiniDFSCluster.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSStartupWithCRL.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/TestYarnStartupWithCRL.java
https://hopshadoop.atlassian.net/browse/HOPS-1265
Bug fix for tests
=> [HOPS-1265]  Change NN binding address to 0.0.0.0 and use the FQDN in tests instead of hostname

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/SysInfo.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/SysInfoLinux.java, hadoop-tools/hadoop-gridmix/src/test/java/org/apache/hadoop/mapred/gridmix/DummyResourceCalculatorPlugin.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/test/java/org/apache/hadoop/yarn/conf/TestYarnConfigurationFields.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/ResourceCalculatorPlugin.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/io/hops/devices/GPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/io/hops/devices/GPUAllocator.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandlerGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/NodeManagerHardwareUtils.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestCgroupsLCEResourcesHandlerAMDGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestCgroupsLCEResourcesHandlerNVIDIAGPU.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestGPUAllocatorAMD.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/util/TestGPUAllocatorNVIDIA.java, pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1111
=> [HOPS-1111] Support AMD GPUs as a schedulable and isolable resource

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/QuotaUpdateManager.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1314
bug fix
=> [HOPS-1314] fix NullPointerException in QuotaUpdateManager

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/DBRMStateStore.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1216
Bug fix
depends on hopshadoop/hops-metadata-dal#160 and hopshadoop/hops-metadata-dal-impl-ndb#200
=> [HOPS-1216] fix Tupple does not exist when deleting application attempts

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/StorageType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSOutputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsConstants.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockStoragePolicySuite.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestBlockStoragePolicy.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSSSLServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFileSeek.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesQuota.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestReadOnlySharedStorage.java
https://hopshadoop.atlassian.net/browse/HOPS-1215?filter=-1
https://github.com/hopshadoop/hops-metadata-dal/pull/158
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/199
=> [HOPS-1215] Set storage type for Small Files stored in the database

README.md
=> [HOPS-1317] Include building instructions for hops-gpu-management-impl-amd

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BRTrackingService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockReportLoadBalancing1.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1214
https://github.com/hopshadoop/hops-metadata-dal/pull/161
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/202
=> [HOPS-1214] Blockreport load balancing per NN

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/metrics/TestNameNodeMetrics.java
https://hopshadoop.atlassian.net/browse/HOPS-1322
Bug fix
=> [HOPS-1322] fix TestNameNodeMetrics

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestPendingReplication.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1315
Bug fix
=> [HOPS-1315] fix NullPointerException in PROCESS_TIMEDOUT_PENDING_BLOCK

hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1318
=> [HOPS-1318] fixing compatibility with hdfs-mount

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLeaseManager.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1323?filter=allopenissues
=> [HOPS-1323] Fix removing leases

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/INodesLocks.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/balancer/Dispatcher.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/balancer/TestBalancer.java
https://hopshadoop.atlassian.net/browse/HOPS-1320
Bug fix
Speed up adding blocks during block reporting and avoid ongoing block report overwriting forced block report trigger.
Depends on hopshadoop/hops-metadata-dal#163
=> [HOPS-1320] fix TestBalancer

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestHAFileCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLockUpgradeInFileRead.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSuppressTransientExceptions.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1313
https://github.com/hopshadoop/hops-metadata-dal/pull/159
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/201
=> [HOPS-1313] Suppress transient exceptions

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/LightWeightCacheDistributed.java
https://hopshadoop.atlassian.net/browse/HOPS-1325
Bug fix
=> [HOPS-1325] Retry cache return only if in DB

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockScanner.java
https://hopshadoop.atlassian.net/browse/HOPS-1330
bug fix
=> [HOPS-1330] fix TestBlockScanner.testMultipleBlockPoolScanning

README.md
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1321
Bug fix
=> [HOPS-1321] fix ndb address in README

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1326
bug fix
=> [HOPS-1326] make block adding batch size in processReport configurable

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
https://hopshadoop.atlassian.net/browse/HOPS-1331
bug fix
=> [HOPS-1331] DFSClient.setQuotaByStorageType call on leaderNN

hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.js, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/explorer.html
https://hopshadoop.atlassian.net/browse/HOPS-1333
Bug fix
=> [HOPS-1333] fix NN web UI

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RpcSSLEngine.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RpcSSLEngineAbstr.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/ServerRpcSSLEngineImpl.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/TimeWatch.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml
https://hopshadoop.atlassian.net/browse/HOPS-1327
Bug fix
=> [HOPS-1327] Measure time spent during TLS handshake and throw SSLExceptions when something goes wrong

README.md, pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1332?filter=allopenissues
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/203
=> [HOPS-1332] Ugrade to NDB 7.6.10

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/HopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestHopsworksRMAppSecurityActions.java
https://hopshadoop.atlassian.net/browse/HOPS-1335
Bug fix
=> [HOPS-1335] Fallback to application submitter if fail to extract Hopsworks username

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/DatanodeProtocolClientSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/DatanodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPServiceActor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/DatanodeProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/DatanodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockManager.java
[HOPS-1112] Fix firstBlockReport check in BlockManager for Multi NN
https://hopshadoop.atlassian.net/browse/HOPS-1156
https://hopshadoop.atlassian.net/browse/HOPS-1112
=> [HOPS-1156] Fix datanode not stale variable for Multi NN

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/BaseReplicaContext.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java
https://hopshadoop.atlassian.net/browse/HOPS-1336
=> [HOPS-1336] Fixed rename operation for under replicated files

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NamenodeFsck.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsck.java
https://hopshadoop.atlassian.net/browse/HOPS-163
=> [HOPS-163] Fixed Fsck for small files

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/test/java/org/apache/hadoop/yarn/conf/TestYarnConfigurationFields.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/HopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/MockJWTIssuer.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestHopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestX509SecurityHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/MockHopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/src/test/java/org/apache/hadoop/yarn/server/TestYarnStartupWithCRL.java
[HOPS-1311]  Make paths configurable
[HOPS-1311]  Fix TestYarnStartupWithCRL test after new service JWT renew protocol
[HOPS-1311]  Configurable service JWT validity period
[HOPS-1311]  Change JWT API
[HOPS-1311] Fixes
[HOPS-1311] Build data transfer objects
[HOPS-1311] Fix typo in DTO field name
[HOPS-1311] Fix bug with expiration date format
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1033
Bug fix
New renew protocol for service JWT used by the ResourceManager(s)
* **Does this PR introduce a breaking change?** (What changes might …
=> [HOPS-1311]  Adapt service JWT renewer to new protocol

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-1338
bug fix
=> [HOPS-1338] fix RetryCacheCleaner throw OutOfMemoryError

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1340
=> [HOPS-1340] Fixed the logs for deleted blocks

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RpcSSLEngineAbstr.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Server.java
[HOPS-1334] Add some logs
[HOPS-1334] Make connection null after closing it
https://hopshadoop.atlassian.net/browse/HOPS-1334
Improvement
=> [HOPS-1334] Move TLS handshake and CRL validation to Reader threads

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/AbstractHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/LocalResourceHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/SuperUserHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java
https://hopshadoop.atlassian.net/browse/HOPS-1342
Improvement
=> [HOPS-1342] Remove hostname/fqdn check from SuperUserHopsSSLCheck

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-1359
https://hopshadoop.atlassian.net/browse/HOPS-1360
https://hopshadoop.atlassian.net/browse/HOPS-1361
https://hopshadoop.atlassian.net/browse/HOPS-1362
Depends on hopshadoop/hops-metadata-dal#176 and hopshadoop/hops-metadata-dal-impl-ndb#208
=> [HOPS-1359], [HOPS-1360], [HOPS-1361], and[HOPS-1362]

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMRestart.java
https://hopshadoop.atlassian.net/browse/HOPS-1358
Bug fix
=> [HOPS-1358] Fix NPE when NM was re-syncing with RM and had a wrong state of running applications

hadoop-project/pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1357
=> [HOPS-1357] Bump Gson dependency version

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BaseINodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/INodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/INodesLocks.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DatanodeStorageInfo.java
https://hopshadoop.atlassian.net/browse/HOPS-1367
Bug fix
=> [HOPS-1367] fix locking in addStoredBlockTx

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceTrackerService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/RMAppImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMRestart.java
https://hopshadoop.atlassian.net/browse/HOPS-1370
Bug fix
=> [HOPS-1370] Fix NPE when enabling JWT and restart RM with running apps

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeys.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CommandWithDestination.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CopyCommands.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/ParallelCommandWithDestination.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/PathData.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-common-project/hadoop-common/src/test/resources/testConf.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestInodeChildrenCount.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMultithreadedCopyToOrFromLocal.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestPutCLIWithMultiNN.java
https://hopshadoop.atlassian.net/browse/HOPS-1349
=> [HOPS-1349] Optimizing copyFromLocal & copyToLocal HopsFS CLI

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPServiceActor.java
https://hopshadoop.atlassian.net/browse/HOPS-1376
bug fix
=> [HOPS-1376] fix deadlock in BPServiceActor.offerService

hadoop-hdfs-project/hadoop-hdfs/src/test/resources/log4j.properties
https://hopshadoop.atlassian.net/browse/HOPS-1375
bug fix
=> [HOPS-1375] remove test.log from hdfs

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java
https://hopshadoop.atlassian.net/browse/HOPS-1389
Bug fix
=> [HOPS-1389] Fix NullPointerException when running FSCK

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BaseEncodingStatusLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirConcatOp.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestHDFSConcat.java
https://hopshadoop.atlassian.net/browse/HOPS-1390
Bug fix
=> [HOPS-1390] HDFS concat keep srcs order Export

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/MockNM.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestX509SecurityHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1387
Test bug fix
=> [HOPS-1387] Fix wrong NM response ID that failed the test

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroupsCache.java
https://hopshadoop.atlassian.net/browse/HOPS-1392
=> [HOPS-1393] Optimized UG Cache for deleted users/groups

README.txt, dev-support/bin/dist-layout-stitching, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1399
bug fix
=> [HOPS-1399] fix dist profile

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/FinishedContainerResourcesUsage.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/PriceMultiplicatorService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaComputeEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaContainerFinishEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaContainerStartEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaContainerUpdateEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaEvent.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaEventType.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/yarn/server/resourcemanager/quota/QuotaService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMContext.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMContextImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMServiceContext.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/rmcontainer/RMContainerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/AbstractYarnScheduler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/io/hops/yarn/server/resourcemanager/quota/TestPriceMultiplicationFactorService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/io/hops/yarn/server/resourcemanager/quota/TestQuotaService.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/MockAM.java
https://hopshadoop.atlassian.net/browse/HOPS-1385
Refactor of feature
https://docs.google.com/document/d/1LJ_1QzkZBhrE-Gs5mY-4-EX2lZuTpOd6qxjy2HYxdmc/edit?usp=sharing
depends on hopshadoop/hops-metadata-dal#171 and hopshadoop/hops-metadata-dal-impl-ndb#211
=> [HOPS-1385] redo the Yarn quota system for hadoop 3

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSOutputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSOutputStream.java, hadoop-project/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/reader/AbstractTimelineReaderHBaseTestBase.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/TestHBaseTimelineStorageApps.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/TestHBaseTimelineStorageDomain.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/TestHBaseTimelineStorageEntities.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/TestHBaseTimelineStorageSchema.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/TestTimelineReaderHBaseDown.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/flow/TestHBaseStorageFlowActivity.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/flow/TestHBaseStorageFlowRun.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase-tests/src/test/java/org/apache/hadoop/yarn/server/timelineservice/storage/flow/TestHBaseStorageFlowRunCompaction.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-server/hadoop-yarn-server-timelineservice-hbase-server-2/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-timelineservice-hbase/hadoop-yarn-server-timelineservice-hbase-server/hadoop-yarn-server-timelineservice-hbase-server-2/src/assembly/coprocessor.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1379
new feature
Add support for Hbase 2 for Yarn TimelineService
depends on hopshadoop/hops-metadata-dal-impl-ndb#213
=> [HOPS-1379] make support for hbase 2 compile and pass tests

hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestGetBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestOverReplicatedBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockReplacement.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestBlockReport2.java
https://hopshadoop.atlassian.net/browse/HOPS-1391
bug fix
=> [HOPS-1391] fix TestGetBlocks

hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/libexec/shellprofile.d/hadoop-httpfs.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/distribute-exclude.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs-config.cmd, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs-config.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/hdfs.cmd, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/refresh-namenodes.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/start-balancer.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/start-dfs.cmd, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/start-dfs.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/start-secure-dns.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/stop-balancer.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/stop-dfs.cmd, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/stop-dfs.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/bin/stop-secure-dns.sh, hadoop-hdfs-project/hadoop-hdfs/src/main/shellprofile.d/hadoop-hdfs.sh
https://hopshadoop.atlassian.net/browse/HOPS-1405
bug fix
=> [HOPS-1405] HDFS running scripts

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java, hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/resources/GetOpParam.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/fs/Hdfs.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/XAttrHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/web/resources/NamenodeWebHdfsMethods.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/JsonUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/WebHdfsFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/xattr.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroupsMultiNamenode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/FSXAttrBaseTest.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestJsonUtil.java
https://hopshadoop.atlassian.net/browse/HOPS-1415
https://hopshadoop.atlassian.net/browse/HOPS-1416
tests: https://bbc1.sics.se/jenkins/view/maism/job/hops-maism/50/
=> [Hops 1415][Hops 1416]

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/DevRemoteCRLFetcher.java
https://hopshadoop.atlassian.net/browse/HOPS-1480
bug fix
=> [HOPS-1480] add DevRemoteCRLFetcher

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/amlauncher/AMLauncher.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestApplicationMasterLauncher.java
https://hopshadoop.atlassian.net/browse/HOPS-1482
Bug fix
=> [HOPS-1482] Fix bug revoking security material even when there is another app attempt

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java
https://hopshadoop.atlassian.net/browse/HOPS-1483
=> [HOPS-1483] Track changes on the metadaEnabled directory

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/security/token/block/NameNodeBlockTokenSecretManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/security/token/block/BlockKey.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/security/token/block/BlockTokenSecretManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1510
Bug fix and refactoring
=> [HOPS-1510] refactor NameNodeBlockTokenSecretManager

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/RootINodeCache.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/common/HdfsServerConstants.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/MDCleaner.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/QuotaUpdateManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-api/src/main/java/org/apache/hadoop/yarn/conf/YarnConfiguration.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/util/RMStorageFactory.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/DBRMStateStore.java
https://hopshadoop.atlassian.net/browse/HOPS-1516
bug fix
depends on hopshadoop/hops-metadata-dal#181 and hopshadoop/hops-metadata-dal-impl-ndb#221
=> [HOPS-1516] stop NN and RM when the db is dead

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/io/hops/util/DBUtility.java
https://hopshadoop.atlassian.net/browse/HOPS-1519
Bug fix
Don't call System.exit in yarn tests
=> [HOPS-1519] don't call System.exit in yarn tests

hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/pom.xml, hadoop-maven-plugins/pom.xml, hadoop-project/pom.xml, hadoop-tools/hadoop-tools-dist/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/pom.xml, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1517
=> [HOPS-1517] update clover to opensource version

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/yarn-default.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/DBRMStateStore.java
https://hopshadoop.atlassian.net/browse/HOPS-1522#
bug fix
=> [HOPS-1522] fix DBRMStateStore.checkAvailableResources

hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestEncryptionZones.java
https://hopshadoop.atlassian.net/browse/HOPS-1520
bug fix
=> [HOPS-1520] fix TestEncryptionZones on branch 3

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestEncryptionZonesWithKMS.java
https://hopshadoop.atlassian.net/browse/HOPS-1523
bug fix
=> [HOPS-1523] fix TestEncryptionZonesWithKMS on branch 3.2.0.0 

hadoop-project/pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1521
=> [HOPS-1521] bump up version of netty-all and jackson-databind

hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsFileStatus.java, hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/JsonUtilClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSOutputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DataStreamer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/HdfsLocatedFileStatus.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockStoragePolicySuite.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirStatAndListingOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/web/JsonUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSClientRetries.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestEncryptionZones.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLease.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFsck.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestJsonUtil.java
https://hopshadoop.atlassian.net/browse/HOPS-1374
=> [HOPS-1374] Fixing Hdfsstatus to contain storage policy

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesDiskFull.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1531?filter=myopenissues&orderby=priority%20DESC
=> [HOPS-1531] More unit tests for small files

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsUtil.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/hopssslchecks/LocalResourceHopsSSLCheck.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/SSLFactory.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/io/TestHopsUtil.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-app/src/main/java/org/apache/hadoop/mapreduce/v2/app/launcher/ContainerLauncherImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-client/src/main/java/org/apache/hadoop/yarn/client/api/impl/NMClientImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/ContainerManagerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/container/ContainerImpl.java
https://hopshadoop.atlassian.net/browse/HOPS-1536
Bug fix
=> [HOPS-1536] make keyStore, trustStore and password path configurable

pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1539?filter=allopenissues&orderby=created%20DESC
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/223
=> [HOPS-1539] Bump NDB version 7.6.10 -> 7.6.12

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSetrepIncreasing.java
https://hopshadoop.atlassian.net/browse/HOPS-1545
bug fix
=> [HOPS-1545] apply HDFS-9625

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FileProvenance.java
https://hopshadoop.atlassian.net/browse/HOPS-1546
bug fix
=> [HOPS-1546] unchecked cast in provenance code leads to cast exception

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsSecurityActionsFactory.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/ServiceJWTManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestHopsworksFsSecurityActions.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestWebHDFSHopsTLS.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapred/ClusterMapReduceTestCase.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapreduce/security/ssl/TestEncryptedShuffle.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/test/java/org/apache/hadoop/yarn/applications/distributedshell/TestDistributedShell.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAppSecurityManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/TestRMAppTransitions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestHopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestJWTSecurityHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestX509SecurityHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1547
Bug fix
No breaking changes
=> [HOPS-1547] Fix deadlock bug in ServiceJWTManager

README.md, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/security/TestHopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/KeyStoreTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestWebHDFSHopsTLS.java
https://hopshadoop.atlassian.net/browse/HOPS-1549
Check JIRA description
https://bbc1.sics.se/jenkins/job/hops-pull/432/
=> [HOPS-1549] Do not set appId for WebHDFS x509 authentication

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGenerator.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGeneratorFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/QuotaUpdateManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestInodeIDgeneration.java
https://hopshadoop.atlassian.net/browse/HOPS-1554
bug fix
=> [HOPS-1154] Fixed HopsFS rapid ID generation bug

README.md, hadoop-client-modules/hadoop-client-minicluster/pom.xml, hadoop-client-modules/hadoop-client/pom.xml, hadoop-common-project/hadoop-common/pom.xml, hadoop-common-project/hadoop-common/src/main/java/io/hops/net/ServiceDiscoveryClientFactory.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsSecurityActionsFactory.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/security/ServiceJWTManager.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-common-project/hadoop-common/src/test/java/io/hops/security/TestHopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/KeyStoreTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGenerator.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/common/IDsGeneratorFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/IndividualBlockLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/QuotaUpdateManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestHopsworksFsSecurityActions.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestWebHDFSHopsTLS.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestInodeIDgeneration.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapred/ClusterMapReduceTestCase.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/src/test/java/org/apache/hadoop/mapreduce/security/ssl/TestEncryptedShuffle.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-distributedshell/src/test/java/org/apache/hadoop/yarn/applications/distributedshell/TestDistributedShell.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/security/RMAppSecurityManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/rmapp/TestRMAppTransitions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestHopsworksRMAppSecurityActions.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestJWTSecurityHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/security/TestX509SecurityHandler.java, pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1557
bug fix
Get commit from master in and [HOPS-1557]
=> [HOPS-1557]

hadoop-client-modules/hadoop-client-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
https://hopshadoop.atlassian.net/browse/HOPS-1558
bug fix
=> [HOPS-1558] accept android handler from consul 

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/container/ContainerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/TestContainerManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1559
Bug fix
=> [HOPS-1559] Fix propagation of updated security material at Containers

hadoop-common-project/hadoop-common/src/main/java/io/hops/net/ServiceDiscoveryClientFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/main/resources/core-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1560
Task
=> [HOPS-1560] Use system's configured nameserver by default

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/HopsX509Authenticator.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/security/TestHopsX509Authenticator.java
https://hopshadoop.atlassian.net/browse/HOPS-1561
Bug fix
=> [HOPS-1561] Do not do a reverse DNS lookup on the incoming RPC IP to authenticate a user, do a forward lookup on the CN instead

README.md, pom.xml
=> HOPSWORKS-1765 archiva

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/adaptor/ReplicaUnderConstructionDALAdaptor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/BaseReplicaContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/ReplicaContext.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/transaction/lock/TestInodeLock.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestCommitBlockSynchronization.java
https://hopshadoop.atlassian.net/browse/HOPS-1564
https://github.com/hopshadoop/hops-metadata-dal/pull/189
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/231
=> [HOPS-1564] Fixed bug in transaction cache

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirAclOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/FSAclBaseTest.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSubtreeLockACL.java
https://hopshadoop.atlassian.net/browse/HOPS-1562
https://hopshadoop.atlassian.net/browse/HOPS-1563
Bug fixes
=> [HOPS-1563] and [HOPS-1562]

pom.xml
=> fix missed repo change

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirXAttrOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FileProvenance.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/XAttrFeature.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/XAttrStorage.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestMetadataLog.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLargeXAttr.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNamenodeRetryCache.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/XAttrTestHelpers.java
https://hopshadoop.atlassian.net/browse/HOPS-1568
improvement
https://github.com/hopshadoop/hops-metadata-dal/pull/190
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/233
https://github.com/logicalclocks/hops-docs/pull/157
=> [HOPS-1568] Add support for large XAttrs (>13500)

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/SuperuserKeystoresLoader.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/security/TestSuperuserKeystoresLoader.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/crypto/TestHopsSSLConfiguration.java
https://hopshadoop.atlassian.net/browse/HOPS-1579
Bug fix
=> [HOPS-1579] Get superuser username from the login user

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirDeleteOp.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFSDirDeleteACL.java
https://hopshadoop.atlassian.net/browse/HOPS-1583
=> [HOPS-1583] Access storage exception on ACLs when calling delete

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1585
=> [HOPS-1585] replica under construction fix

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDecommission.java
https://hopshadoop.atlassian.net/browse/HOPS-1587
=> [HOPS-1587] call refreshNodes on the leader NN

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LeaseLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LeasePathLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseRecovery3.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLeaseManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1590
=> [HOPS-1590] Fix lease manager for rename operation

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java
- [ l] All commits have been squashed down to a single commit
https://hopshadoop.atlassian.net/browse/HOPS-1592
=> [HOPS-1592] Fix block count in block report

pom.xml
need https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/241
=> Upgrade to NDB 8

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/RootINodeCache.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSOutputStream.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/LastUpdatedContentSummary.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirAttrOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INode.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/INodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/DFSTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSmallFilesQuota.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSmallFilesDiskspaceQuotaUpdate.java
https://hopshadoop.atlassian.net/browse/HOPS-1614
https://github.com/logicalclocks/hops-hadoop-chef/pull/283
=> [HOPS-1614] Fix quota calculations

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestUnderReplicatedBlocks.java
=> [HOPS-1605] ADENDUM

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java
https://hopshadoop.atlassian.net/browse/HOPS-1616
bug fix
=> [HOPS-1616] fix checksum

hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/resources/PermissionParam.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/web/webhdfs/ParameterParser.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/web/resources/NamenodeWebHdfsMethods.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/web/resources/TestWebHdfsCreatePermissions.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/resources/TestParam.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/security/TestPermission.java
https://hopshadoop.atlassian.net/browse/HOPS-1619
https://hopshadoop.atlassian.net/browse/HOPS-1620
Bug fix
=> [HOPS-1620][HOPS-1619]

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/source/JvmMetrics.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/source/JvmMetricsInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsStorageFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeMXBean.java, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.html, hadoop-hdfs-project/hadoop-hdfs/src/main/webapps/hdfs/dfshealth.js
https://github.com/hopshadoop/hops-metadata-dal/pull/201
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/249
=> [HOPSWORKS-CLOUD-1598] Added direct mem and DB utilization to HopsFS UI

hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLeaseManager.java
=> [HOPSWORKS-CLOUD-1621] Fixed TestLeaseManager

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CommandWithDestination.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CopyCommands.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/ParallelCommandWithDestination.java
=> [HOPSWORKS-CLOUD-1737] Fix creating multiple clients for copyFromLocal

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/webapp/util/WebAppUtils.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/test/java/org/apache/hadoop/yarn/webapp/util/TestWebAppUtils.java
=> [HOPS-1628] Use TLS for Yarn web UI

hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/DistCpConstants.java, hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/DistCpOptionSwitch.java, hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/DistCpOptions.java, hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/OptionsParser.java, hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/mapred/CopyMapper.java, hadoop-tools/hadoop-distcp/src/main/java/org/apache/hadoop/tools/mapred/RetriableFileCopyCommand.java, hadoop-tools/hadoop-distcp/src/site/markdown/DistCp.md.vm, hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/TestDistCpOptions.java, hadoop-tools/hadoop-distcp/src/test/java/org/apache/hadoop/tools/contract/AbstractContractDistCpTest.java
=> HADOOP-15281 - Distcp to add no-rename copy option.

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/AbstractFileTree.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java
https://hopshadoop.atlassian.net/browse/HOPS-1630
=> [HOPS-1630] Reduce subtree lock back size

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java
=> [HOPS-1632] Reduce quota manager batch size

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/DatanodeProtocolClientSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/DatanodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPOfferService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/BPServiceActor.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/protocol/DatanodeProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/DatanodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreationDelete.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/DataNodeTestUtils.java
* https://hopshadoop.atlassian.net/browse/HOPS-1631
=> [HOPS-1631] Improved handling of failed incremental block reports

hadoop-hdfs-project/hadoop-hdfs/src/test/resources/testHDFSConf.xml, pom.xml
=> [HOPS-1625] RonDB 21.04.0

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
https://hopshadoop.atlassian.net/browse/HOPS-1633
=> [HOPS-1633] Fix missing locks for under construction replica

hadoop-hdfs-project/hadoop-hdfs/src/test/resources/testHDFSConf.xml, pom.xml
This reverts commit 2cc0e395c8b1ce63b65c14aee343cf4a7450a7e6.
=> Revert "[HOPS-1625] RonDB 21.04.0"

hadoop-hdfs-project/hadoop-hdfs/src/test/resources/testHDFSConf.xml, pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1635
* https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/253
=> [HOPS-1635] RonDB 21.04.0 and configurable ClusterJ caching

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestMultiNNURI.java
* https://hopshadoop.atlassian.net/browse/HOPS-1634
=> [HOPS-1634] Fix uri checks for multi-namenode deployments using consul

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java
* https://hopshadoop.atlassian.net/browse/HOPS-1637
=> [HOPS-1637] NPE in getBlockLocations when all sotrages are dead

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto
* https://hopshadoop.atlassian.net/browse/HOPS-1639
=> [HOPS-1639] Fixed conflicting protocol buffer message IDs

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/INodeContext.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/context/RootINodeCache.java
=> [HOPS-1643] NPE fix while reading cached root inode

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileUtil.java, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-uploader/src/test/java/org/apache/hadoop/mapred/uploader/TestFrameworkUploader.java, hadoop-project/pom.xml
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Akira Ajisaka <aajisaka@apache.org>
Signed-off-by: Wei-Chiu Chuang <weichiu@apache.org>
https://hopshadoop.atlassian.net/browse/HOPS-1641
=> [HOPS-1641] HADOOP-17683. Update commons-io to 2.8.0 (#2974)

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/CertificateLocalizationService.java
https://hopshadoop.atlassian.net/browse/HOPS-1649
=> [HOPS-1649] Add Livy option to CertificateLocalizationService

hadoop-common-project/hadoop-common/src/main/java/io/hops/security/UsersGroupsCache.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/BlockManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hops-leader-election/src/main/java/io/hops/leaderElection/LeaderElection.java
https://hopshadoop.atlassian.net/browse/HOPS-1654
* https://hopshadoop.atlassian.net/browse/HOPS-1654
* https://github.com/hopshadoop/hops/pull/884
* https://github.com/hopshadoop/hops-metadata-dal/pull/205
* https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/260
* https://github.com/logicalclocks/hops-hadoop-chef/pull/351
* https://github.com/logicalclocks/rondb/pull/80
*
=> [HOPS-1654] Reconnect to NDB after network failure

pom.xml
=> [HOPSWORKS-3174] Bump-up RonDB version to 21.04.6

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/test/java/org/apache/hadoop/yarn/server/resourcemanager/TestRMHA.java
https://hopshadoop.atlassian.net/browse/HOPS-1659
Bug fix
No
=> [HOPS-1659] Transfer the CertificateLocalizationService to the new RM Context when transitioning from Active to StandBy

hadoop-project/pom.xml
=> HOPSFS-19: Bump version of commons-text due to CVE-2022-42889

pom.xml
=> HOPSFS-18: Using RonDB 21.04.9

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Client.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketFactory.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/HopsSSLSocketWrapper.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509KeyManager.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509TrustManager.java, hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/TestReloadingX509TrustManager.java
=> [HOPSFS-28] Properly close Reloading key managers from Client

pom.xml
=> HOPSFS-52: Bumped RonDB to 21.04.10

pom.xml
=> Revert "HOPSFS-52: Bumped RonDB to 21.04.10"

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/metadata/HdfsVariables.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestReplicationPolicy.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestINodeFile.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestProcessCorruptBlocks.java, hadoop-hdfs-project/hadoop-hdfs/src/test/resources/log4j2.properties, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/DBRMStateStore.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/capacity/conf/DBConfigurationStore.java, hops-leader-election/src/main/java/io/hops/leaderElection/VarsRegister.java, pom.xml
=> Hopsfs 57 se

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/XAttrLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileCreation.java
=> HOPSFS-64: Batch lock XAttr

hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/BaseCGroupsCpuResourceHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/BaseCGroupsHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/BaseCGroupsMemoryResourceHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroupElasticMemoryController.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroups2CpuResourceHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroups2HandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroups2MemoryResourceHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroupsCpuResourceHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroupsHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/CGroupsHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/DefaultOOMHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/ResourceHandlerModule.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/util/CgroupsLCEResourcesHandler.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/TestCGroups2HandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/TestCGroupsCpuResourceHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/TestCGroupsHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/TestCGroupsMemoryResourceHandlerImpl.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/test/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/resources/TestDefaultOOMHandler.java
https://hopsworks.atlassian.net/browse/CLOUD-430
https://hopsworks.atlassian.net/browse/HOPSFS-74
=> [CLOUD-430 HOPSFS-74] Support for group2

dev-support/docker/Dockerfile, start-build-env.sh
=> [HOPSFS-89] fix DockerFile to build in docker

hadoop-client-modules/hadoop-client-minicluster/pom.xml, hadoop-client-modules/hadoop-client-runtime/pom.xml, hadoop-project/pom.xml, pom.xml
=> HOPSFS-85, HOPSFS-86 HOPSFS-87 HOPSFS-88

dev-support/docker/Dockerfile, pom.xml, start-build-env.sh, test.jenkinsfile
=> Hopsfs 113

test.jenkinsfile
=> [HOPSFS-120] Fix jenkins test pipeline to work without parameters

deploy.jenkinsfile
=> Hopsfs 121

deploy.jenkinsfile, test.jenkinsfile
https://hopsworks.atlassian.net/browse/HOPSFS-122
=> [HOPSFS-122] Remove -SNAPSHOT from RonDB version

pom.xml
=> RONDB-384: Bump RonDB version to 21.04.13

deploy.jenkinsfile
https://hopsworks.atlassian.net/browse/HOPSFS-122
=> [HOPSFS-122] append - SNAPSHOT should not be removed during deployment

pom.xml
=> RONDB-394: Bump RonDB version to 21.04.14

pom.xml
=> RONDB-458: Bump RonDB Version to 21.04.15

hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/AliveWatchdogPoller.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/AliveWatchdogService.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/HttpPageNotFoundPoller.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/HttpUtils.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/JsonPoller.java, hadoop-common-project/hadoop-common/src/main/java/io/hops/leader_election/watchdog/NoopPoller.java, hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/CommonConfigurationKeysPublic.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/leader_election/watchdog/TestHttpPageNotFoundPoller.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/leader_election/watchdog/TestJsonPoller.java, hadoop-common-project/hadoop-common/src/test/java/io/hops/leader_election/watchdog/TestWatchdogService.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNode.java, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/ResourceManager.java
* [HOPSFS-124] Daemon which periodically consults an external service whether the service should be alive or not
[HOPSFS-124] Start AliveWatchdog service in NameNode and ResourceManager
[HOPSFS-124] Poller class which is based on the HTTP status of a webserver
* [HOPSFS-124] Optionally configure truststore
* [HOPSFS-124] Move responsibility of checking whether the service should be enabled or not to the caller
* [HOPSFS-124] Throw exception if watchdog service is enabled but no poller class is configured
* [HOPSFS-124] Implement HTTP poller parsing json response
* [HOPSFS-124] No lowercase
* [HOPSFS-124] Add license
* **What kind of change does this PR introduce?** (Bug fix, feature, …
=> [HOPSFS-124] Daemon which periodically consults an external service whether the service should be alive or not

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/BaseINodeLock.java
=> HOPSFS-147: Fix NPC INode Locks

deploy.jenkinsfile
=> HOPSFS-154: Fix deployment on jenkins

hadoop-hdfs-project/hadoop-hdfs/src/main/native/libhdfs-golang/libhdfs.go
=> HOPSFS-155: Libhdfs fix getting system user name

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DataStreamer.java, pom.xml
RONDB-661 RonDB minor release 22.10.3
=> RONDB-661 RonDB minor release 22.10.3

hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LeaseCreationLockComparator.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LeaseLock.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/lock/LockFactory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirDeleteOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestLeaseCreationLock.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockInfo.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockInfoUnderConstruction.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestHeartbeatHandling.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAddBlockRetry.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestCommitBlockSynchronization.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFileTruncate.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestLeaseManager.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestQuotaByStorageType.java
=> HOPSFS-158: Fixed Lease Locks

hadoop-client-modules/hadoop-client-minicluster/pom.xml, hadoop-common-project/hadoop-common/pom.xml, hadoop-common-project/hadoop-kms/pom.xml, hadoop-hdfs-project/hadoop-hdfs-httpfs/pom.xml, hadoop-hdfs-project/hadoop-hdfs/pom.xml, hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient/pom.xml, hadoop-project/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/pom.xml, hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-tests/pom.xml
https://hopsworks.atlassian.net/browse/HOPSFS-157
=> [HOPSFS-157] [HOPSFS-157] Bump BouncyCastle version (#224)

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/LeaseManager.java
=> HOPSFS-158: Addendum. Fixed compilation error

test.jenkinsfile
=> HOPSFS-163: Fixed test.jenkinsfile

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestRetryCacheCleaner.java
=> HOPSFS-162: Fixed Retry Cache Cleaner

test.jenkinsfile
=> HOPSFS-174: Update Rondb-docker to 0.6

hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/security/ssl/KeyStoreTestUtil.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/erasure_coding/ErasureCodingManager.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/io/hops/transaction/handler/HDFSOperationType.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSClient.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocol/ClientProtocol.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolServerSideTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/ClientNamenodeProtocolTranslatorPB.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirStatAndListingOp.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirectory.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/ClientNamenodeProtocol.proto, hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto, hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestUsersGroupsMultiNamenode.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/NameNodeAdapter.java
=> HOPSFS-172: RPC compatibility with hadoop 3.2 clients

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/fs/Hdfs.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestUnicode.java
=> Port HOPSFS-189 and HOPSFS-182 to 3.2.0.14

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java, hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/fs/Hdfs.java
=> HOPSFS-182: Fixed AbstractFileSystem for hopsfs scheme

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java, hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestUnicode.java
=> HOPSFS-189: Check that the paths conform to latin1_general_cs collation

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java
=> HOPSFS-189: Addendum Fixed Compilation

hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSConfigKeys.java, hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml
=> HOPSFS-222: Fixed config variables for subtree operations
